### ISSUE TITLE
SyntaxError: Unexpected token s in JSON at position 0

### ISSUE THREAD

**Issue by MHuiG** [Lete114/cache-hash#4]
在这里可以复现

https://www.json.cn/runcode/run_javascript/

```
JSON.parse([['script', 'src'], ['link', 'href'], ['img', 'src']])
```

```
编译错误：
Runtime Error (NZEC)
执行错误：
undefined:1
script,src,link,href,img,src
^

SyntaxError: Unexpected token s in JSON at position 0
    at JSON.parse ()
    at Object. (/box/script.js:1:6)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
```

https://github.com/volantis-x/community/actions/runs/6739804617/job/18321927123

```
> cache-hash --target public --output public

undefined:1
script,src,link,href,img,src
^

SyntaxError: Unexpected token s in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/home/runner/work/community/community/node_modules/cache-hash/bin/cache-hash:41:26)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47
```

**Comment by lete114** [comment]
因该是已经修复了。但还没有发布到npm
